### PR TITLE
Release 1.0

### PR DESCRIPTION
**Pull request by Haacked**
This is a release branch for Scientist.NET 1.0.0. I believe we've implemented everything needed to call this a 1.0.

My plan is to release this in a couple weeks because I'm traveling next week.

I'll also move it to the https://github.com/github organization  as it will be the official C# port.

### CODE REVIEW

**Comment by davezych** [comment]
I'm assuming you're hoping to get #71 done before this release? Like I said I'm hoping to get to it, but I've been _way_ busy recently and it's not looking like it's going to lighten up anytime soon.

**Comment by Haacked** [comment]
@davezych #71 just changes the development environment, right? It doesn't affect the NuGet package produced? If that's the case, it can happen after 1.0 released.

**Comment by joncloud** [comment]
I think you're right @Haacked.  The output should still be the same `.dll` packaged up regardless of how the `.dll` was created (.csproj vs project.json).

**Comment by davezych** [comment]
Hey @Haacked what's the status of the 1.0 release? Are we waiting on anything?

**Comment by Haacked** [comment]
@davezych One more thing. Thanks for asking! I want to move it to the github org and am just making sure the others who started Scientist are cool with that.

**Comment by Haacked** [comment]
This has been published! It's currently being indexed by NuGet, but should show up soon.

**Comment by davezych** [comment]
Whooooooo! 🙌

**Comment by Haacked** [comment]
It's live! I wrote a blog post about it. http://haacked.com/archive/2016/09/29/scientist-1.0-released/

Thanks y'all! Couldn't have done it without you. :smile:

**Comment by davezych** [comment]
I just noticed the docs still say "it's a rough sketch...". I can fix and submit a PR in a bit, but if you have time it should probably be updated.

**Comment by Haacked** [comment]
Please do!

**Pull request merged**
